### ISSUE TITLE
可否开发mac版本？

### ISSUE THREAD

**Issue by caesarljs** [miaomiaosoft/PandaOCR#73]
目前在win上使用非常好用，可否尝试开发mac版本呢

**Comment by fish2302** [comment]
+1 ，灰常好用的软件，同求mac版本

**Comment by miaomiaosoft** [comment]
你俩是一伙的么！
https://github.com/miaomiaosoft/PandaOCR/issues/62
我连MAC都没有，就不用想了

**Comment by fish2302** [comment]
被拆穿了吗。。那，小姐姐你要mac吗




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            lxybiz
                            
                            
                                
                                    邮箱：lxybiz@sina.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


在2019年11月01日 17:37，miao_miao 写道： Closed #73.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/miaomiaosoft/PandaOCR/issues/73?email_source=notifications\u0026email_token=AFKNPICSX4UNFUS4AJY6ZFDQRP2EBA5CNFSM4JHYI4K2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUSVKKYQ#event-2762646882",
"url": "https://github.com/miaomiaosoft/PandaOCR/issues/73?email_source=notifications\u0026email_token=AFKNPICSX4UNFUS4AJY6ZFDQRP2EBA5CNFSM4JHYI4K2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUSVKKYQ#event-2762646882",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by miaomiaosoft** [comment]
就算给我MAC也没用滴，开发语言也并没有MAC版本
![75D%L8YGSLZY03CE`_HVX`A](https://user-images.githubusercontent.com/4084875/68026394-942c7880-fcea-11e9-991d-7bba68ee86b1.gif)

**Comment by fish2302** [comment]
哼，所以这么晚才回复意味着你刚下班么，勉强原谅你好啦




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            lxybiz
                            
                            
                                
                                    邮箱：lxybiz@sina.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


在2019年11月01日 21:00，miao_miao 写道： 就算给我MAC也没用滴，开发语言也并没有MAC版本



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/miaomiaosoft/PandaOCR/issues/73?email_source=notifications\u0026email_token=AFKNPIGSZO7PVTWXSX5SJK3QRQR6DA5CNFSM4JHYI4K2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEC23IMQ#issuecomment-548779058",
"url": "https://github.com/miaomiaosoft/PandaOCR/issues/73?email_source=notifications\u0026email_token=AFKNPIGSZO7PVTWXSX5SJK3QRQR6DA5CNFSM4JHYI4K2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEC23IMQ#issuecomment-548779058",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by yeyuguo** [comment]
+1 ，灰常好用的软件，同求mac版本
